import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // AUTO-GENERATED reference data block for prisma/seed.ts
  // Wilayas: complete official list of all 58 wilayas (codes 1-48 per Law 84-09/1984,
  // codes 49-58 added by Law 19-12/2019).
  // Communes: full, accurate commune list for wilayas 1-15 (474 communes).
  // For wilayas 16-58, only the chef-lieu (capital) commune is seeded for now —
  // add the remaining communes for those wilayas as your customer base needs them.
  const wilayas = [
    { id: 1, code: '01', nameFr: 'Adrar', nameAr: 'أدرار' },
    { id: 2, code: '02', nameFr: 'Chlef', nameAr: 'الشلف' },
    { id: 3, code: '03', nameFr: 'Laghouat', nameAr: 'الأغواط' },
    { id: 4, code: '04', nameFr: 'Oum El Bouaghi', nameAr: 'أم البواقي' },
    { id: 5, code: '05', nameFr: 'Batna', nameAr: 'باتنة' },
    { id: 6, code: '06', nameFr: 'Béjaïa', nameAr: 'بجاية' },
    { id: 7, code: '07', nameFr: 'Biskra', nameAr: 'بسكرة' },
    { id: 8, code: '08', nameFr: 'Béchar', nameAr: 'بشار' },
    { id: 9, code: '09', nameFr: 'Blida', nameAr: 'البليدة' },
    { id: 10, code: '10', nameFr: 'Bouira', nameAr: 'البويرة' },
    { id: 11, code: '11', nameFr: 'Tamanrasset', nameAr: 'تمنراست' },
    { id: 12, code: '12', nameFr: 'Tébessa', nameAr: 'تبسة' },
    { id: 13, code: '13', nameFr: 'Tlemcen', nameAr: 'تلمسان' },
    { id: 14, code: '14', nameFr: 'Tiaret', nameAr: 'تيارت' },
    { id: 15, code: '15', nameFr: 'Tizi Ouzou', nameAr: 'تيزي وزو' },
    { id: 16, code: '16', nameFr: 'Alger', nameAr: 'الجزائر' },
    { id: 17, code: '17', nameFr: 'Djelfa', nameAr: 'الجلفة' },
    { id: 18, code: '18', nameFr: 'Jijel', nameAr: 'جيجل' },
    { id: 19, code: '19', nameFr: 'Sétif', nameAr: 'سطيف' },
    { id: 20, code: '20', nameFr: 'Saïda', nameAr: 'سعيدة' },
    { id: 21, code: '21', nameFr: 'Skikda', nameAr: 'سكيكدة' },
    { id: 22, code: '22', nameFr: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس' },
    { id: 23, code: '23', nameFr: 'Annaba', nameAr: 'عنابة' },
    { id: 24, code: '24', nameFr: 'Guelma', nameAr: 'قالمة' },
    { id: 25, code: '25', nameFr: 'Constantine', nameAr: 'قسنطينة' },
    { id: 26, code: '26', nameFr: 'Médéa', nameAr: 'المدية' },
    { id: 27, code: '27', nameFr: 'Mostaganem', nameAr: 'مستغانم' },
    { id: 28, code: '28', nameFr: 'M\'Sila', nameAr: 'المسيلة' },
    { id: 29, code: '29', nameFr: 'Mascara', nameAr: 'معسكر' },
    { id: 30, code: '30', nameFr: 'Ouargla', nameAr: 'ورقلة' },
    { id: 31, code: '31', nameFr: 'Oran', nameAr: 'وهران' },
    { id: 32, code: '32', nameFr: 'El Bayadh', nameAr: 'البيض' },
    { id: 33, code: '33', nameFr: 'Illizi', nameAr: 'إليزي' },
    { id: 34, code: '34', nameFr: 'Bordj Bou Arréridj', nameAr: 'برج بوعريريج' },
    { id: 35, code: '35', nameFr: 'Boumerdès', nameAr: 'بومرداس' },
    { id: 36, code: '36', nameFr: 'El Tarf', nameAr: 'الطارف' },
    { id: 37, code: '37', nameFr: 'Tindouf', nameAr: 'تندوف' },
    { id: 38, code: '38', nameFr: 'Tissemsilt', nameAr: 'تيسمسيلت' },
    { id: 39, code: '39', nameFr: 'El Oued', nameAr: 'الوادي' },
    { id: 40, code: '40', nameFr: 'Khenchela', nameAr: 'خنشلة' },
    { id: 41, code: '41', nameFr: 'Souk Ahras', nameAr: 'سوق أهراس' },
    { id: 42, code: '42', nameFr: 'Tipaza', nameAr: 'تيبازة' },
    { id: 43, code: '43', nameFr: 'Mila', nameAr: 'ميلة' },
    { id: 44, code: '44', nameFr: 'Aïn Defla', nameAr: 'عين الدفلى' },
    { id: 45, code: '45', nameFr: 'Naâma', nameAr: 'النعامة' },
    { id: 46, code: '46', nameFr: 'Aïn Témouchent', nameAr: 'عين تموشنت' },
    { id: 47, code: '47', nameFr: 'Ghardaïa', nameAr: 'غرداية' },
    { id: 48, code: '48', nameFr: 'Relizane', nameAr: 'غليزان' },
    { id: 49, code: '49', nameFr: 'Timimoun', nameAr: 'تيميمون' },
    { id: 50, code: '50', nameFr: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار' },
    { id: 51, code: '51', nameFr: 'Ouled Djellal', nameAr: 'أولاد جلال' },
    { id: 52, code: '52', nameFr: 'Béni Abbès', nameAr: 'بني عباس' },
    { id: 53, code: '53', nameFr: 'In Salah', nameAr: 'عين صالح' },
    { id: 54, code: '54', nameFr: 'In Guezzam', nameAr: 'عين قزام' },
    { id: 55, code: '55', nameFr: 'Touggourt', nameAr: 'تقرت' },
    { id: 56, code: '56', nameFr: 'Djanet', nameAr: 'جانت' },
    { id: 57, code: '57', nameFr: 'El M\'Ghair', nameAr: 'المغير' },
    { id: 58, code: '58', nameFr: 'El Meniaa', nameAr: 'المنيعة' }
  ];
  
  const communes = [
    { id: 22, wilayaId: 1, nameFr: 'Timekten', nameAr: 'تيمقتن' },
    { id: 6, wilayaId: 1, nameFr: 'Bouda', nameAr: 'بودة' },
    { id: 13, wilayaId: 1, nameFr: 'Ouled Ahmed Timmi', nameAr: 'أولاد أحمد تيمي' },
    { id: 1, wilayaId: 1, nameFr: 'Adrar', nameAr: 'أدرار' },
    { id: 9, wilayaId: 1, nameFr: 'Fenoughil', nameAr: 'فنوغيل' },
    { id: 10, wilayaId: 1, nameFr: 'In Zghmir', nameAr: 'إن زغمير' },
    { id: 16, wilayaId: 1, nameFr: 'Reggane', nameAr: 'رقان' },
    { id: 17, wilayaId: 1, nameFr: 'Sali', nameAr: 'سالي' },
    { id: 18, wilayaId: 1, nameFr: 'Sebaa', nameAr: 'السبع' },
    { id: 27, wilayaId: 1, nameFr: 'Tsabit', nameAr: 'تسابيت' },
    { id: 21, wilayaId: 1, nameFr: 'Tamest', nameAr: 'تامست' },
    { id: 20, wilayaId: 1, nameFr: 'Tamantit', nameAr: 'تامنطيط' },
    { id: 26, wilayaId: 1, nameFr: 'Tit', nameAr: 'تيت' },
    { id: 28, wilayaId: 1, nameFr: 'Zaouiet Kounta', nameAr: 'زاوية كنتة' },
    { id: 2, wilayaId: 1, nameFr: 'Akabli', nameAr: 'اقبلي' },
    { id: 4, wilayaId: 1, nameFr: 'Aoulef', nameAr: 'أولف' },
    { id: 60, wilayaId: 2, nameFr: 'Talassa', nameAr: 'تلعصة' },
    { id: 63, wilayaId: 2, nameFr: 'Zeboudja', nameAr: 'الزبوجة' },
    { id: 41, wilayaId: 2, nameFr: 'El Hadjadj', nameAr: 'الحجاج' },
    { id: 52, wilayaId: 2, nameFr: 'Ouled Ben Abdelkader', nameAr: 'أولاد بن عبد القادر' },
    { id: 30, wilayaId: 2, nameFr: 'Ain Merane', nameAr: 'عين مران' },
    { id: 37, wilayaId: 2, nameFr: 'Breira', nameAr: 'بريرة' },
    { id: 51, wilayaId: 2, nameFr: 'Ouled Abbes', nameAr: 'أولاد عباس' },
    { id: 48, wilayaId: 2, nameFr: 'Oued Fodda', nameAr: 'وادي الفضة' },
    { id: 34, wilayaId: 2, nameFr: 'Beni Rached', nameAr: 'بني راشد' },
    { id: 45, wilayaId: 2, nameFr: 'Herenfa', nameAr: 'الهرانفة' },
    { id: 59, wilayaId: 2, nameFr: 'Tadjena', nameAr: 'تاجنة' },
    { id: 43, wilayaId: 2, nameFr: 'El Marsa', nameAr: 'المرسى' },
    { id: 39, wilayaId: 2, nameFr: 'Chlef', nameAr: 'الشلف' },
    { id: 54, wilayaId: 2, nameFr: 'Oum Drou', nameAr: 'أم الدروع' },
    { id: 55, wilayaId: 2, nameFr: 'Sendjas', nameAr: 'سنجاس' },
    { id: 56, wilayaId: 2, nameFr: 'Sidi Abderrahmane', nameAr: 'سيدي عبد الرحمن' },
    { id: 57, wilayaId: 2, nameFr: 'Sidi Akkacha', nameAr: 'سيدي عكاشة' },
    { id: 62, wilayaId: 2, nameFr: 'Tenes', nameAr: 'تنس' },
    { id: 32, wilayaId: 2, nameFr: 'Beni Bouattab', nameAr: 'بني بوعتاب' },
    { id: 42, wilayaId: 2, nameFr: 'El Karimia', nameAr: 'الكريمية' },
    { id: 44, wilayaId: 2, nameFr: 'Harchoun', nameAr: 'حرشون' },
    { id: 36, wilayaId: 2, nameFr: 'Bouzeghaia', nameAr: 'بوزغاية' },
    { id: 61, wilayaId: 2, nameFr: 'Taougrit', nameAr: 'تاوقريت' },
    { id: 33, wilayaId: 2, nameFr: 'Beni Haoua', nameAr: 'بني حواء' },
    { id: 29, wilayaId: 2, nameFr: 'Abou El Hassane', nameAr: 'أبو الحسن' },
    { id: 49, wilayaId: 2, nameFr: 'Oued Goussine', nameAr: 'وادي قوسين' },
    { id: 38, wilayaId: 2, nameFr: 'Chettia', nameAr: 'الشطية' },
    { id: 47, wilayaId: 2, nameFr: 'Moussadek', nameAr: 'مصدق' },
    { id: 53, wilayaId: 2, nameFr: 'Ouled Fares', nameAr: 'أولاد فارس' },
    { id: 35, wilayaId: 2, nameFr: 'Boukadir', nameAr: 'بوقادير' },
    { id: 50, wilayaId: 2, nameFr: 'Oued Sly', nameAr: 'وادي سلي' },
    { id: 58, wilayaId: 2, nameFr: 'Sobha', nameAr: 'الصبحة' },
    { id: 31, wilayaId: 2, nameFr: 'Benairia', nameAr: 'بنايرية' },
    { id: 46, wilayaId: 2, nameFr: 'Labiod Medjadja', nameAr: 'الأبيض مجاجة' },
    { id: 40, wilayaId: 2, nameFr: 'Dahra', nameAr: 'الظهرة' },
    { id: 67, wilayaId: 3, nameFr: 'El Beidha', nameAr: 'البيضاء' },
    { id: 73, wilayaId: 3, nameFr: 'Gueltat Sidi Saad', nameAr: 'قلتة سيدي سعد' },
    { id: 69, wilayaId: 3, nameFr: 'Brida', nameAr: 'بريدة' },
    { id: 66, wilayaId: 3, nameFr: 'Ain Sidi Ali', nameAr: 'عين سيدي علي' },
    { id: 85, wilayaId: 3, nameFr: 'Tadjemout', nameAr: 'تاجموت' },
    { id: 74, wilayaId: 3, nameFr: 'Hadj Mechri', nameAr: 'الحاج مشري' },
    { id: 87, wilayaId: 3, nameFr: 'Taouiala', nameAr: 'تاويالة' },
    { id: 71, wilayaId: 3, nameFr: 'El Ghicha', nameAr: 'الغيشة' },
    { id: 86, wilayaId: 3, nameFr: 'Tadjrouna', nameAr: 'تاجرونة' },
    { id: 82, wilayaId: 3, nameFr: 'Sebgag', nameAr: 'سبقاق' },
    { id: 83, wilayaId: 3, nameFr: 'Sidi Bouzid', nameAr: 'سيدي بوزيد' },
    { id: 80, wilayaId: 3, nameFr: 'Oued Morra', nameAr: 'وادي مرة' },
    { id: 79, wilayaId: 3, nameFr: 'Laghouat', nameAr: 'الأغواط' },
    { id: 81, wilayaId: 3, nameFr: 'Oued Mzi', nameAr: 'وادي مزي' },
    { id: 78, wilayaId: 3, nameFr: 'Ksar El Hirane', nameAr: 'قصر الحيران' },
    { id: 70, wilayaId: 3, nameFr: 'El Assafia', nameAr: 'العسافية' },
    { id: 84, wilayaId: 3, nameFr: 'Sidi Makhlouf', nameAr: 'سيدي مخلوف' },
    { id: 75, wilayaId: 3, nameFr: 'Hassi Delaa', nameAr: 'حاسي الدلاعة' },
    { id: 76, wilayaId: 3, nameFr: 'Hassi Rmel', nameAr: 'حاسي الرمل' },
    { id: 65, wilayaId: 3, nameFr: 'Ain Madhi', nameAr: 'عين ماضي' },
    { id: 72, wilayaId: 3, nameFr: 'El Haouaita', nameAr: 'الحويطة' },
    { id: 77, wilayaId: 3, nameFr: 'Kheneg', nameAr: 'الخنق' },
    { id: 68, wilayaId: 3, nameFr: 'Benacer Benchohra', nameAr: 'بن ناصر بن شهرة' },
    { id: 64, wilayaId: 3, nameFr: 'Aflou', nameAr: 'أفلو' },
    { id: 104, wilayaId: 4, nameFr: 'Fkirina', nameAr: 'فكيرينة' },
    { id: 102, wilayaId: 4, nameFr: 'El Fedjoudj Boughrara Sa', nameAr: 'الفجوج بوغرارة سعودي' },
    { id: 91, wilayaId: 4, nameFr: 'Ain Fekroun', nameAr: 'عين فكرون' },
    { id: 113, wilayaId: 4, nameFr: 'Rahia', nameAr: 'الرحية' },
    { id: 107, wilayaId: 4, nameFr: 'Meskiana', nameAr: 'مسكيانة' },
    { id: 100, wilayaId: 4, nameFr: 'El Belala', nameAr: 'البلالة' },
    { id: 95, wilayaId: 4, nameFr: 'Behir Chergui', nameAr: 'بحير الشرقي' },
    { id: 106, wilayaId: 4, nameFr: 'Ksar Sbahi', nameAr: 'قصر الصباحي' },
    { id: 115, wilayaId: 4, nameFr: 'Souk Naamane', nameAr: 'سوق نعمان' },
    { id: 111, wilayaId: 4, nameFr: 'Ouled Zouai', nameAr: 'أولاد زواي' },
    { id: 112, wilayaId: 4, nameFr: 'Oum El Bouaghi', nameAr: 'أم البواقي' },
    { id: 88, wilayaId: 4, nameFr: 'Ain Babouche', nameAr: 'عين ببوش' },
    { id: 94, wilayaId: 4, nameFr: 'Ain Zitoun', nameAr: 'عين الزيتون' },
    { id: 97, wilayaId: 4, nameFr: 'Bir Chouhada', nameAr: 'بئر الشهداء' },
    { id: 89, wilayaId: 4, nameFr: 'Ain Beida', nameAr: 'عين البيضاء' },
    { id: 96, wilayaId: 4, nameFr: 'Berriche', nameAr: 'بريش' },
    { id: 116, wilayaId: 4, nameFr: 'Zorg', nameAr: 'الزرق' },
    { id: 93, wilayaId: 4, nameFr: 'Ain Mlila', nameAr: 'عين مليلة' },
    { id: 109, wilayaId: 4, nameFr: 'Ouled Gacem', nameAr: 'أولاد قاسم' },
    { id: 110, wilayaId: 4, nameFr: 'Ouled Hamla', nameAr: 'أولاد حملة' },
    { id: 99, wilayaId: 4, nameFr: 'El Amiria', nameAr: 'العامرية' },
    { id: 114, wilayaId: 4, nameFr: 'Sigus', nameAr: 'سيقوس' },
    { id: 108, wilayaId: 4, nameFr: 'Oued Nini', nameAr: 'وادي نيني' },
    { id: 90, wilayaId: 4, nameFr: 'Ain Diss', nameAr: 'عين الديس' },
    { id: 98, wilayaId: 4, nameFr: 'Dhalaa', nameAr: 'الضلعة' },
    { id: 101, wilayaId: 4, nameFr: 'El Djazia', nameAr: 'الجازية' },
    { id: 92, wilayaId: 4, nameFr: 'Ain Kercha', nameAr: 'عين كرشة' },
    { id: 103, wilayaId: 4, nameFr: 'El Harmilia', nameAr: 'الحرملية' },
    { id: 105, wilayaId: 4, nameFr: 'Hanchir Toumghani', nameAr: 'هنشير تومغني' },
    { id: 150, wilayaId: 5, nameFr: 'Maafa', nameAr: 'معافة' },
    { id: 139, wilayaId: 5, nameFr: 'Gosbat', nameAr: 'القصبات' },
    { id: 176, wilayaId: 5, nameFr: 'Timgad', nameAr: 'تيمقاد' },
    { id: 170, wilayaId: 5, nameFr: 'Taxlent', nameAr: 'تاكسلانت' },
    { id: 161, wilayaId: 5, nameFr: 'Ouled Si Slimane', nameAr: 'أولاد سي سليمان' },
    { id: 148, wilayaId: 5, nameFr: 'Lemcene', nameAr: 'لمسان' },
    { id: 169, wilayaId: 5, nameFr: 'Talkhamt', nameAr: 'تالخمت' },
    { id: 164, wilayaId: 5, nameFr: 'Ras El Aioun', nameAr: 'رأس العيون' },
    { id: 163, wilayaId: 5, nameFr: 'Rahbat', nameAr: 'الرحبات' },
    { id: 160, wilayaId: 5, nameFr: 'Ouled Sellem', nameAr: 'أولاد سلام' },
    { id: 140, wilayaId: 5, nameFr: 'Guigba', nameAr: 'القيقبة' },
    { id: 172, wilayaId: 5, nameFr: 'Teniet El Abed', nameAr: 'ثنية العابد' },
    { id: 123, wilayaId: 5, nameFr: 'Batna', nameAr: 'باتنة' },
    { id: 136, wilayaId: 5, nameFr: 'Fesdis', nameAr: 'فسديس' },
    { id: 154, wilayaId: 5, nameFr: 'Oued Chaaba', nameAr: 'وادي الشعبة' },
    { id: 141, wilayaId: 5, nameFr: 'Hidoussa', nameAr: 'حيدوسة' },
    { id: 145, wilayaId: 5, nameFr: 'Ksar Bellezma', nameAr: 'قصر بلزمة' },
    { id: 152, wilayaId: 5, nameFr: 'Merouana', nameAr: 'مروانة' },
    { id: 155, wilayaId: 5, nameFr: 'Oued El Ma', nameAr: 'وادي الماء' },
    { id: 147, wilayaId: 5, nameFr: 'Lazrou', nameAr: 'لازرو' },
    { id: 167, wilayaId: 5, nameFr: 'Seriana', nameAr: 'سريانة' },
    { id: 177, wilayaId: 5, nameFr: 'Zanet El Beida', nameAr: 'زانة البيضاء' },
    { id: 151, wilayaId: 5, nameFr: 'Menaa', nameAr: 'منعة' },
    { id: 174, wilayaId: 5, nameFr: 'Tigharghar', nameAr: 'تغرغار' },
    { id: 119, wilayaId: 5, nameFr: 'Ain Yagout', nameAr: 'عين ياقوت' },
    { id: 128, wilayaId: 5, nameFr: 'Boumia', nameAr: 'بومية' },
    { id: 132, wilayaId: 5, nameFr: 'Djerma', nameAr: 'جرمة' },
    { id: 135, wilayaId: 5, nameFr: 'El Madher', nameAr: 'المعذر' },
    { id: 162, wilayaId: 5, nameFr: 'Ouyoun El Assafir', nameAr: 'عيون العصافير' },
    { id: 171, wilayaId: 5, nameFr: 'Tazoult', nameAr: 'تازولت' },
    { id: 127, wilayaId: 5, nameFr: 'Boumagueur', nameAr: 'بومقر' },
    { id: 153, wilayaId: 5, nameFr: 'N Gaous', nameAr: 'نقاوس' },
    { id: 165, wilayaId: 5, nameFr: 'Sefiane', nameAr: 'سفيان' },
    { id: 120, wilayaId: 5, nameFr: 'Arris', nameAr: 'أريس' },
    { id: 173, wilayaId: 5, nameFr: 'Tighanimine', nameAr: 'تيغانمين' },
    { id: 117, wilayaId: 5, nameFr: 'Ain Djasser', nameAr: 'عين جاسر' },
    { id: 134, wilayaId: 5, nameFr: 'El Hassi', nameAr: 'الحاسي' },
    { id: 166, wilayaId: 5, nameFr: 'Seggana', nameAr: 'سقانة' },
    { id: 175, wilayaId: 5, nameFr: 'Tilatou', nameAr: 'تيلاطو' },
    { id: 137, wilayaId: 5, nameFr: 'Foum Toub', nameAr: 'فم الطوب' },
    { id: 142, wilayaId: 5, nameFr: 'Ichemoul', nameAr: 'إشمول' },
    { id: 143, wilayaId: 5, nameFr: 'Inoughissen', nameAr: 'إينوغيسن' },
    { id: 129, wilayaId: 5, nameFr: 'Bouzina', nameAr: 'بوزينة' },
    { id: 146, wilayaId: 5, nameFr: 'Larbaa', nameAr: 'لارباع' },
    { id: 126, wilayaId: 5, nameFr: 'Boulhilat', nameAr: 'بولهيلات' },
    { id: 130, wilayaId: 5, nameFr: 'Chemora', nameAr: 'الشمرة' },
    { id: 122, wilayaId: 5, nameFr: 'Barika', nameAr: 'بريكة' },
    { id: 125, wilayaId: 5, nameFr: 'Bitam', nameAr: 'بيطام' },
    { id: 149, wilayaId: 5, nameFr: 'M Doukal', nameAr: 'إمدوكل' },
    { id: 121, wilayaId: 5, nameFr: 'Azil Abedelkader', nameAr: 'عزيل عبد القادر' },
    { id: 133, wilayaId: 5, nameFr: 'Djezzar', nameAr: 'الجزار' },
    { id: 157, wilayaId: 5, nameFr: 'Ouled Ammar', nameAr: 'أولاد عمار' },
    { id: 138, wilayaId: 5, nameFr: 'Ghassira', nameAr: 'غسيرة' },
    { id: 144, wilayaId: 5, nameFr: 'Kimmel', nameAr: 'كيمل' },
    { id: 168, wilayaId: 5, nameFr: 'T Kout', nameAr: 'تكوت' },
    { id: 118, wilayaId: 5, nameFr: 'Ain Touta', nameAr: 'عين التوتة' },
    { id: 124, wilayaId: 5, nameFr: 'Beni Foudhala El Hakania', nameAr: 'بني فضالة الحقانية' },
    { id: 159, wilayaId: 5, nameFr: 'Ouled Fadel', nameAr: 'أولاد فاضل' },
    { id: 158, wilayaId: 5, nameFr: 'Ouled Aouf', nameAr: 'أولاد عوف' },
    { id: 131, wilayaId: 5, nameFr: 'Chir', nameAr: 'شير' },
    { id: 156, wilayaId: 5, nameFr: 'Oued Taga', nameAr: 'وادي الطاقة' },
    { id: 212, wilayaId: 6, nameFr: 'Sidi Ayad', nameAr: 'سيدي عياد' },
    { id: 186, wilayaId: 6, nameFr: 'Barbacha', nameAr: 'برباشة' },
    { id: 199, wilayaId: 6, nameFr: 'Leflaye', nameAr: 'الفلاي' },
    { id: 206, wilayaId: 6, nameFr: 'Kendira', nameAr: 'كنديرة' },
    { id: 213, wilayaId: 6, nameFr: 'Sidi-Aich', nameAr: 'سيدي عيش' },
    { id: 225, wilayaId: 6, nameFr: 'Tifra', nameAr: 'تيفرة' },
    { id: 227, wilayaId: 6, nameFr: 'Tinebdar', nameAr: 'تينبدار' },
    { id: 200, wilayaId: 6, nameFr: 'El Kseur', nameAr: 'القصر' },
    { id: 201, wilayaId: 6, nameFr: 'Fenaia Il Maten', nameAr: 'فناية الماثن' },
    { id: 229, wilayaId: 6, nameFr: 'Toudja', nameAr: 'توجة' },
    { id: 198, wilayaId: 6, nameFr: 'Dra El Caid', nameAr: 'ذراع القايد' },
    { id: 207, wilayaId: 6, nameFr: 'Kherrata', nameAr: 'خراطة' },
    { id: 187, wilayaId: 6, nameFr: 'Bejaia', nameAr: 'بجاية' },
    { id: 210, wilayaId: 6, nameFr: 'Oued Ghir', nameAr: 'وادي غير' },
    { id: 191, wilayaId: 6, nameFr: 'Benimaouche', nameAr: 'بني معوش' },
    { id: 188, wilayaId: 6, nameFr: 'Beni Djellil', nameAr: 'بني جليل' },
    { id: 202, wilayaId: 6, nameFr: 'Feraoun', nameAr: 'فرعون' },
    { id: 214, wilayaId: 6, nameFr: 'Smaoun', nameAr: 'سمعون' },
    { id: 226, wilayaId: 6, nameFr: 'Timezrit', nameAr: 'تيمزريت' },
    { id: 209, wilayaId: 6, nameFr: 'Melbou', nameAr: 'مالبو' },
    { id: 215, wilayaId: 6, nameFr: 'Souk El Tenine', nameAr: 'سوق لإثنين' },
    { id: 219, wilayaId: 6, nameFr: 'Tamridjet', nameAr: 'تامريجت' },
    { id: 194, wilayaId: 6, nameFr: 'Boukhelifa', nameAr: 'بوخليفة' },
    { id: 217, wilayaId: 6, nameFr: 'Tala Hamza', nameAr: 'تالة حمزة' },
    { id: 224, wilayaId: 6, nameFr: 'Tichy', nameAr: 'تيشي' },
    { id: 179, wilayaId: 6, nameFr: 'Ait Rzine', nameAr: 'أيت رزين' },
    { id: 204, wilayaId: 6, nameFr: 'Ighil-Ali', nameAr: 'إغيل علي' },
    { id: 180, wilayaId: 6, nameFr: 'Ait-Smail', nameAr: 'أيت إسماعيل' },
    { id: 197, wilayaId: 6, nameFr: 'Darguina', nameAr: 'درقينة' },
    { id: 221, wilayaId: 6, nameFr: 'Taskriout', nameAr: 'تاسكريوت' },
    { id: 185, wilayaId: 6, nameFr: 'Aokas', nameAr: 'أوقاس' },
    { id: 228, wilayaId: 6, nameFr: 'Tizi-Nberber', nameAr: 'تيزي نبربر' },
    { id: 178, wilayaId: 6, nameFr: 'Adekar', nameAr: 'أدكار' },
    { id: 189, wilayaId: 6, nameFr: 'Beni Ksila', nameAr: 'بني كسيلة' },
    { id: 220, wilayaId: 6, nameFr: 'Taourit Ighil', nameAr: 'تاوريرت إغيل' },
    { id: 181, wilayaId: 6, nameFr: 'Akbou', nameAr: 'أقبو' },
    { id: 195, wilayaId: 6, nameFr: 'Chellata', nameAr: 'شلاطة' },
    { id: 205, wilayaId: 6, nameFr: 'Ighram', nameAr: 'اغرم' },
    { id: 218, wilayaId: 6, nameFr: 'Tamokra', nameAr: 'تامقرة' },
    { id: 183, wilayaId: 6, nameFr: 'Amalou', nameAr: 'أمالو' },
    { id: 193, wilayaId: 6, nameFr: 'Bouhamza', nameAr: 'بوحمزة' },
    { id: 208, wilayaId: 6, nameFr: 'Mcisna', nameAr: 'مسيسنة' },
    { id: 211, wilayaId: 6, nameFr: 'Seddouk', nameAr: 'صدوق' },
    { id: 190, wilayaId: 6, nameFr: 'Beni-Mallikeche', nameAr: 'بني مليكش' },
    { id: 192, wilayaId: 6, nameFr: 'Boudjellil', nameAr: 'بو جليل' },
    { id: 222, wilayaId: 6, nameFr: 'Tazmalt', nameAr: 'تازمالت' },
    { id: 182, wilayaId: 6, nameFr: 'Akfadou', nameAr: 'أكفادو' },
    { id: 196, wilayaId: 6, nameFr: 'Chemini', nameAr: 'شميني' },
    { id: 216, wilayaId: 6, nameFr: 'Souk Oufella', nameAr: 'سوق اوفلا' },
    { id: 223, wilayaId: 6, nameFr: 'Tibane', nameAr: 'طيبان' },
    { id: 203, wilayaId: 6, nameFr: 'Ouzellaguen', nameAr: 'أوزلاقن' },
    { id: 184, wilayaId: 6, nameFr: 'Amizour', nameAr: 'أميزور' },
    { id: 241, wilayaId: 7, nameFr: 'El Feidh', nameAr: 'الفيض' },
    { id: 249, wilayaId: 7, nameFr: 'Lichana', nameAr: 'ليشانة' },
    { id: 235, wilayaId: 7, nameFr: 'Bouchakroun', nameAr: 'بوشقرون' },
    { id: 252, wilayaId: 7, nameFr: 'Mekhadma', nameAr: 'مخادمة' },
    { id: 239, wilayaId: 7, nameFr: 'Djemorah', nameAr: 'جمورة' },
    { id: 236, wilayaId: 7, nameFr: 'Branis', nameAr: 'برانيس' },
    { id: 246, wilayaId: 7, nameFr: 'El Outaya', nameAr: 'الوطاية' },
    { id: 245, wilayaId: 7, nameFr: 'El Kantara', nameAr: 'القنطرة' },
    { id: 248, wilayaId: 7, nameFr: 'Khenguet Sidi Nadji', nameAr: 'خنقة سيدي ناجي' },
    { id: 231, wilayaId: 7, nameFr: 'Ain Zaatout', nameAr: 'عين زعطوط' },
    { id: 262, wilayaId: 7, nameFr: 'Zeribet El Oued', nameAr: 'زريبة الوادي' },
    { id: 253, wilayaId: 7, nameFr: 'Meziraa', nameAr: 'المزيرعة' },
    { id: 233, wilayaId: 7, nameFr: 'Biskra', nameAr: 'بسكرة' },
    { id: 243, wilayaId: 7, nameFr: 'El Hadjab', nameAr: 'الحاجب' },
    { id: 254, wilayaId: 7, nameFr: 'Mlili', nameAr: 'مليلي' },
    { id: 247, wilayaId: 7, nameFr: 'Foughala', nameAr: 'فوغالة' },
    { id: 242, wilayaId: 7, nameFr: 'El Ghrous', nameAr: 'الغروس' },
    { id: 234, wilayaId: 7, nameFr: 'Bordj Ben Azzouz', nameAr: 'برج بن عزوز' },
    { id: 257, wilayaId: 7, nameFr: 'Ourlal', nameAr: 'أورلال' },
    { id: 256, wilayaId: 7, nameFr: 'Oumache', nameAr: 'أوماش' },
    { id: 230, wilayaId: 7, nameFr: 'Ain Naga', nameAr: 'عين الناقة' },
    { id: 238, wilayaId: 7, nameFr: 'Chetma', nameAr: 'شتمة' },
    { id: 244, wilayaId: 7, nameFr: 'El Haouch', nameAr: 'الحوش' },
    { id: 260, wilayaId: 7, nameFr: 'Sidi Okba', nameAr: 'سيدي عقبة' },
    { id: 251, wilayaId: 7, nameFr: 'Mchouneche', nameAr: 'مشونش' },
    { id: 250, wilayaId: 7, nameFr: 'Lioua', nameAr: 'ليوة' },
    { id: 261, wilayaId: 7, nameFr: 'Tolga', nameAr: 'طولقة' },
    { id: 264, wilayaId: 8, nameFr: 'Bechar', nameAr: 'بشار' },
    { id: 268, wilayaId: 8, nameFr: 'Boukais', nameAr: 'بوكايس' },
    { id: 275, wilayaId: 8, nameFr: 'Lahmar', nameAr: 'لحمر' },
    { id: 278, wilayaId: 8, nameFr: 'Mogheul', nameAr: 'موغل' },
    { id: 277, wilayaId: 8, nameFr: 'Meridja', nameAr: 'المريجة' },
    { id: 281, wilayaId: 8, nameFr: 'Taghit', nameAr: 'تاغيت' },
    { id: 263, wilayaId: 8, nameFr: 'Abadla', nameAr: 'العبادلة' },
    { id: 270, wilayaId: 8, nameFr: 'Erg-Ferradj', nameAr: 'عرق فراج' },
    { id: 276, wilayaId: 8, nameFr: 'Machraa-Houari-Boumediene', nameAr: 'مشرع هواري بومدين' },
    { id: 267, wilayaId: 8, nameFr: 'Beni-Ounif', nameAr: 'بني ونيف' },
    { id: 280, wilayaId: 8, nameFr: 'Tabelbala', nameAr: 'تبلبالة' },
    { id: 272, wilayaId: 8, nameFr: 'Kenadsa', nameAr: 'القنادسة' },
    { id: 285, wilayaId: 9, nameFr: 'Beni Mered', nameAr: 'بني مراد' },
    { id: 305, wilayaId: 9, nameFr: 'Ouled Slama', nameAr: 'اولاد سلامة' },
    { id: 302, wilayaId: 9, nameFr: 'Mouzaia', nameAr: 'موزاية' },
    { id: 299, wilayaId: 9, nameFr: 'Hammam Elouane', nameAr: 'حمام ملوان' },
    { id: 291, wilayaId: 9, nameFr: 'Bougara', nameAr: 'بوقرة' },
    { id: 307, wilayaId: 9, nameFr: 'Souhane', nameAr: 'صوحان' },
    { id: 300, wilayaId: 9, nameFr: 'Larbaa', nameAr: 'الأربعاء' },
    { id: 308, wilayaId: 9, nameFr: 'Soumaa', nameAr: 'الصومعة' },
    { id: 298, wilayaId: 9, nameFr: 'Guerrouaou', nameAr: 'قرواو' },
    { id: 290, wilayaId: 9, nameFr: 'Boufarik', nameAr: 'بوفاريك' },
    { id: 301, wilayaId: 9, nameFr: 'Meftah', nameAr: 'مفتاح' },
    { id: 294, wilayaId: 9, nameFr: 'Chiffa', nameAr: 'الشفة' },
    { id: 284, wilayaId: 9, nameFr: 'Ain Romana', nameAr: 'عين الرمانة' },
    { id: 303, wilayaId: 9, nameFr: 'Oued Djer', nameAr: 'وادي جر' },
    { id: 297, wilayaId: 9, nameFr: 'El-Affroun', nameAr: 'العفرون' },
    { id: 306, wilayaId: 9, nameFr: 'Ouled Yaich', nameAr: 'أولاد يعيش' },
    { id: 295, wilayaId: 9, nameFr: 'Chrea', nameAr: 'الشريعة' },
    { id: 296, wilayaId: 9, nameFr: 'Djebabra', nameAr: 'جبابرة' },
    { id: 304, wilayaId: 9, nameFr: 'Oued El Alleug', nameAr: 'وادي العلايق' },
    { id: 287, wilayaId: 9, nameFr: 'Benkhelil', nameAr: 'بن خليل' },
    { id: 286, wilayaId: 9, nameFr: 'Beni-Tamou', nameAr: 'بني تامو' },
    { id: 293, wilayaId: 9, nameFr: 'Chebli', nameAr: 'الشبلي' },
    { id: 292, wilayaId: 9, nameFr: 'Bouinan', nameAr: 'بوعينان' },
    { id: 289, wilayaId: 9, nameFr: 'Bouarfa', nameAr: 'بوعرفة' },
    { id: 288, wilayaId: 9, nameFr: 'Blida', nameAr: 'البليدة' },
    { id: 312, wilayaId: 10, nameFr: 'Ain Laloui', nameAr: 'عين العلوي' },
    { id: 334, wilayaId: 10, nameFr: 'Hadjera Zerga', nameAr: 'الحجرة الزرقاء' },
    { id: 342, wilayaId: 10, nameFr: 'Mezdour', nameAr: 'مزدور' },
    { id: 351, wilayaId: 10, nameFr: 'Taguedite', nameAr: 'تاقديت' },
    { id: 346, wilayaId: 10, nameFr: 'Ridane', nameAr: 'ريدان' },
    { id: 341, wilayaId: 10, nameFr: 'Maamora', nameAr: 'المعمورة' },
    { id: 331, wilayaId: 10, nameFr: 'El-Hakimia', nameAr: 'الحاكمية' },
    { id: 310, wilayaId: 10, nameFr: 'Ahl El Ksar', nameAr: 'أهل القصر' },
    { id: 325, wilayaId: 10, nameFr: 'Dirah', nameAr: 'ديرة' },
    { id: 324, wilayaId: 10, nameFr: 'Dechmia', nameAr: 'الدشمية' },
    { id: 317, wilayaId: 10, nameFr: 'Bechloul', nameAr: 'بشلول' },
    { id: 352, wilayaId: 10, nameFr: 'Ath Mansour', nameAr: 'آث منصور' },
    { id: 347, wilayaId: 10, nameFr: 'Saharidj', nameAr: 'سحاريج' },
    { id: 327, wilayaId: 10, nameFr: 'El Adjiba', nameAr: 'العجيبة' },
    { id: 328, wilayaId: 10, nameFr: 'El Asnam', nameAr: 'الأسنام' },
    { id: 339, wilayaId: 10, nameFr: 'M Chedallah', nameAr: 'أمشدالة' },
    { id: 319, wilayaId: 10, nameFr: 'Bordj Okhriss', nameAr: 'برج أوخريص' },
    { id: 349, wilayaId: 10, nameFr: 'Sour El Ghozlane', nameAr: 'سور الغزلان' },
    { id: 336, wilayaId: 10, nameFr: 'Hanif', nameAr: 'حنيف' },
    { id: 323, wilayaId: 10, nameFr: 'Chorfa', nameAr: 'شرفة' },
    { id: 344, wilayaId: 10, nameFr: 'Ouled Rached', nameAr: 'أولاد راشد' },
    { id: 311, wilayaId: 10, nameFr: 'Ain El Hadjar', nameAr: 'عين الحجر' },
    { id: 309, wilayaId: 10, nameFr: 'Aghbalou', nameAr: 'أغبالو' },
    { id: 345, wilayaId: 10, nameFr: 'Raouraoua', nameAr: 'روراوة' },
    { id: 330, wilayaId: 10, nameFr: 'El Khabouzia', nameAr: 'الخبوزية' },
    { id: 318, wilayaId: 10, nameFr: 'Bir Ghbalou', nameAr: 'بئر غبالو' },
    { id: 321, wilayaId: 10, nameFr: 'Bouira', nameAr: 'البويرة' },
    { id: 313, wilayaId: 10, nameFr: 'Ain Turk', nameAr: 'عين الترك' },
    { id: 315, wilayaId: 10, nameFr: 'Ait Laaziz', nameAr: 'أيت لعزيز' },
    { id: 314, wilayaId: 10, nameFr: 'Ain-Bessem', nameAr: 'عين بسام' },
    { id: 332, wilayaId: 10, nameFr: 'El-Mokrani', nameAr: 'المقراني' },
    { id: 348, wilayaId: 10, nameFr: 'Souk El Khemis', nameAr: 'سوق الخميس' },
    { id: 316, wilayaId: 10, nameFr: 'Aomar', nameAr: 'أعمر' },
    { id: 326, wilayaId: 10, nameFr: 'Djebahia', nameAr: 'جباحية' },
    { id: 329, wilayaId: 10, nameFr: 'El Hachimia', nameAr: 'الهاشمية' },
    { id: 335, wilayaId: 10, nameFr: 'Haizer', nameAr: 'حيزر' },
    { id: 350, wilayaId: 10, nameFr: 'Taghzout', nameAr: 'تاغزوت' },
    { id: 320, wilayaId: 10, nameFr: 'Bouderbala', nameAr: 'بودربالة' },
    { id: 322, wilayaId: 10, nameFr: 'Boukram', nameAr: 'بوكرم' },
    { id: 333, wilayaId: 10, nameFr: 'Guerrouma', nameAr: 'قرومة' },
    { id: 338, wilayaId: 10, nameFr: 'Lakhdaria', nameAr: 'الأخضرية' },
    { id: 340, wilayaId: 10, nameFr: 'Maala', nameAr: 'معلة' },
    { id: 337, wilayaId: 10, nameFr: 'Kadiria', nameAr: 'قادرية' },
    { id: 343, wilayaId: 10, nameFr: 'Oued El Berdi', nameAr: 'وادي البردي' },
    { id: 362, wilayaId: 11, nameFr: 'Tazrouk', nameAr: 'تاظروك' },
    { id: 354, wilayaId: 11, nameFr: 'Abelsa', nameAr: 'ابلسة' },
    { id: 361, wilayaId: 11, nameFr: 'Tamanrasset', nameAr: 'تمنراست' },
    { id: 355, wilayaId: 11, nameFr: 'Ain Amguel', nameAr: 'عين امقل' },
    { id: 359, wilayaId: 11, nameFr: 'Idles', nameAr: 'أدلس' },
    { id: 380, wilayaId: 12, nameFr: 'El-Houidjbet', nameAr: 'الحويجبات' },
    { id: 379, wilayaId: 12, nameFr: 'El-Aouinet', nameAr: 'العوينات' },
    { id: 381, wilayaId: 12, nameFr: 'Ferkane', nameAr: 'فركان' },
    { id: 385, wilayaId: 12, nameFr: 'Negrine', nameAr: 'نقرين' },
    { id: 368, wilayaId: 12, nameFr: 'Bir Mokkadem', nameAr: 'بئر مقدم' },
    { id: 367, wilayaId: 12, nameFr: 'Bir Dheheb', nameAr: 'بئر الذهب' },
    { id: 388, wilayaId: 12, nameFr: 'Saf Saf El Ouesra', nameAr: 'صفصاف الوسرى' },
    { id: 382, wilayaId: 12, nameFr: 'Guorriguer', nameAr: 'قريقر' },
    { id: 366, wilayaId: 12, nameFr: 'Bekkaria', nameAr: 'بكارية' },
    { id: 371, wilayaId: 12, nameFr: 'Boulhaf Dyr', nameAr: 'بولحاف الدير' },
    { id: 387, wilayaId: 12, nameFr: 'Oum Ali', nameAr: 'أم علي' },
    { id: 370, wilayaId: 12, nameFr: 'Boukhadra', nameAr: 'بوخضرة' },
    { id: 374, wilayaId: 12, nameFr: 'El Malabiod', nameAr: 'الماء الابيض' },
    { id: 386, wilayaId: 12, nameFr: 'Ouenza', nameAr: 'الونزة' },
    { id: 375, wilayaId: 12, nameFr: 'El Meridj', nameAr: 'المريج' },
    { id: 364, wilayaId: 12, nameFr: 'Ain Zerga', nameAr: 'عين الزرقاء' },
    { id: 389, wilayaId: 12, nameFr: 'Stah Guentis', nameAr: 'سطح قنطيس' },
    { id: 377, wilayaId: 12, nameFr: 'El Ogla', nameAr: 'العقلة' },
    { id: 376, wilayaId: 12, nameFr: 'El Mezeraa', nameAr: 'المزرعة' },
    { id: 365, wilayaId: 12, nameFr: 'Bedjene', nameAr: 'بجن' },
    { id: 384, wilayaId: 12, nameFr: 'Morsott', nameAr: 'مرسط' },
    { id: 391, wilayaId: 12, nameFr: 'Telidjen', nameAr: 'ثليجان' },
    { id: 372, wilayaId: 12, nameFr: 'Cheria', nameAr: 'الشريعة' },
    { id: 378, wilayaId: 12, nameFr: 'El Ogla El Malha', nameAr: 'العقلة المالحة' },
    { id: 369, wilayaId: 12, nameFr: 'Bir-El-Ater', nameAr: 'بئر العاتر' },
    { id: 390, wilayaId: 12, nameFr: 'Tebessa', nameAr: 'تبسة' },
    { id: 383, wilayaId: 12, nameFr: 'Hammamet', nameAr: 'الحمامات' },
    { id: 373, wilayaId: 12, nameFr: 'El Kouif', nameAr: 'الكويف' },
    { id: 400, wilayaId: 13, nameFr: 'Bab El Assa', nameAr: 'باب العسة' },
    { id: 441, wilayaId: 13, nameFr: 'Terny Beni Hediel', nameAr: 'تيرني بني هديل' },
    { id: 424, wilayaId: 13, nameFr: 'Mansourah', nameAr: 'منصورة' },
    { id: 404, wilayaId: 13, nameFr: 'Beni Mester', nameAr: 'بني مستر' },
    { id: 394, wilayaId: 13, nameFr: 'Ain Ghoraba', nameAr: 'عين غرابة' },
    { id: 411, wilayaId: 13, nameFr: 'Chetouane', nameAr: 'شتوان' },
    { id: 399, wilayaId: 13, nameFr: 'Amieur', nameAr: 'عمير' },
    { id: 393, wilayaId: 13, nameFr: 'Ain Fezza', nameAr: 'عين فزة' },
    { id: 422, wilayaId: 13, nameFr: 'Honnaine', nameAr: 'هنين' },
    { id: 403, wilayaId: 13, nameFr: 'Beni Khellad', nameAr: 'بني خلاد' },
    { id: 436, wilayaId: 13, nameFr: 'Sidi Djillali', nameAr: 'سيدي الجيلالي' },
    { id: 410, wilayaId: 13, nameFr: 'Bouihi', nameAr: 'البويهي' },
    { id: 427, wilayaId: 13, nameFr: 'Nedroma', nameAr: 'ندرومة' },
    { id: 426, wilayaId: 13, nameFr: 'Msirda Fouaga', nameAr: 'مسيردة الفواقة' },
    { id: 425, wilayaId: 13, nameFr: 'Marsa Ben Mhidi', nameAr: 'مرسى بن مهيدي' },
    { id: 437, wilayaId: 13, nameFr: 'Sidi Medjahed', nameAr: 'سيدي مجاهد' },
    { id: 402, wilayaId: 13, nameFr: 'Beni Boussaid', nameAr: 'بني بوسعيد' },
    { id: 434, wilayaId: 13, nameFr: 'Sebdou', nameAr: 'سبدو' },
    { id: 417, wilayaId: 13, nameFr: 'El Gor', nameAr: 'القور' },
    { id: 414, wilayaId: 13, nameFr: 'El Aricha', nameAr: 'العريشة' },
    { id: 409, wilayaId: 13, nameFr: 'Bouhlou', nameAr: 'بوحلو' },
    { id: 423, wilayaId: 13, nameFr: 'Maghnia', nameAr: 'مغنية' },
    { id: 420, wilayaId: 13, nameFr: 'Hammam Boughrara', nameAr: 'حمام بوغرارة' },
    { id: 444, wilayaId: 13, nameFr: 'Zenata', nameAr: 'زناتة' },
    { id: 430, wilayaId: 13, nameFr: 'Ouled Riyah', nameAr: 'أولاد رياح' },
    { id: 421, wilayaId: 13, nameFr: 'Hennaya', nameAr: 'الحناية' },
    { id: 435, wilayaId: 13, nameFr: 'Sidi Abdelli', nameAr: 'سيدي العبدلي' },
    { id: 440, wilayaId: 13, nameFr: 'Souk Tleta', nameAr: 'سوق الثلاثاء' },
    { id: 408, wilayaId: 13, nameFr: 'Bensekrane', nameAr: 'بن سكران' },
    { id: 418, wilayaId: 13, nameFr: 'Fellaoucene', nameAr: 'فلاوسن' },
    { id: 395, wilayaId: 13, nameFr: 'Ain Kebira', nameAr: 'عين الكبيرة' },
    { id: 392, wilayaId: 13, nameFr: 'Ain Fetah', nameAr: 'عين فتاح' },
    { id: 443, wilayaId: 13, nameFr: 'Tlemcen', nameAr: 'تلمسان' },
    { id: 396, wilayaId: 13, nameFr: 'Ain Nehala', nameAr: 'عين النحالة' },
    { id: 397, wilayaId: 13, nameFr: 'Ain Tellout', nameAr: 'عين تالوت' },
    { id: 398, wilayaId: 13, nameFr: 'Ain Youcef', nameAr: 'عين يوسف' },
    { id: 405, wilayaId: 13, nameFr: 'Beni Ouarsous', nameAr: 'بني وارسوس' },
    { id: 416, wilayaId: 13, nameFr: 'El Fehoul', nameAr: 'الفحول' },
    { id: 431, wilayaId: 13, nameFr: 'Remchi', nameAr: 'الرمشي' },
    { id: 433, wilayaId: 13, nameFr: 'Sebbaa Chioukh', nameAr: 'سبعة شيوخ' },
    { id: 439, wilayaId: 13, nameFr: 'Souani', nameAr: 'السواني' },
    { id: 432, wilayaId: 13, nameFr: 'Sabra', nameAr: 'صبرة' },
    { id: 412, wilayaId: 13, nameFr: 'Dar Yaghmoracen', nameAr: 'دار يغمراسن' },
    { id: 419, wilayaId: 13, nameFr: 'Ghazaouet', nameAr: 'الغزوات' },
    { id: 438, wilayaId: 13, nameFr: 'Souahlia', nameAr: 'السواحلية' },
    { id: 442, wilayaId: 13, nameFr: 'Tianet', nameAr: 'تيانت' },
    { id: 406, wilayaId: 13, nameFr: 'Beni Smiel', nameAr: 'بني صميل' },
    { id: 428, wilayaId: 13, nameFr: 'Oued Lakhdar', nameAr: 'وادي الخضر' },
    { id: 429, wilayaId: 13, nameFr: 'Ouled Mimoun', nameAr: 'أولاد ميمون' },
    { id: 401, wilayaId: 13, nameFr: 'Beni Bahdel', nameAr: 'بني بهدل' },
    { id: 407, wilayaId: 13, nameFr: 'Beni Snous', nameAr: 'بني سنوس' },
    { id: 415, wilayaId: 13, nameFr: 'Azail', nameAr: 'العزايل' },
    { id: 413, wilayaId: 13, nameFr: 'Djebala', nameAr: 'جبالة' },
    { id: 461, wilayaId: 14, nameFr: 'Mahdia', nameAr: 'مهدية' },
    { id: 447, wilayaId: 14, nameFr: 'Ain Dzarit', nameAr: 'عين دزاريت' },
    { id: 472, wilayaId: 14, nameFr: 'Sebaine', nameAr: 'السبعين' },
    { id: 455, wilayaId: 14, nameFr: 'Faidja', nameAr: 'الفايجة' },
    { id: 475, wilayaId: 14, nameFr: 'Si Abdelghani', nameAr: 'سي عبد الغني' },
    { id: 480, wilayaId: 14, nameFr: 'Sougueur', nameAr: 'السوقر' },
    { id: 485, wilayaId: 14, nameFr: 'Tousnina', nameAr: 'توسنينة' },
    { id: 465, wilayaId: 14, nameFr: 'Meghila', nameAr: 'مغيلة' },
    { id: 473, wilayaId: 14, nameFr: 'Sebt', nameAr: 'السبت' },
    { id: 479, wilayaId: 14, nameFr: 'Sidi Hosni', nameAr: 'سيدي حسني' },
    { id: 448, wilayaId: 14, nameFr: 'Ain El Hadid', nameAr: 'عين الحديد' },
    { id: 456, wilayaId: 14, nameFr: 'Frenda', nameAr: 'فرندة' },
    { id: 482, wilayaId: 14, nameFr: 'Takhemaret', nameAr: 'تخمرت' },
    { id: 449, wilayaId: 14, nameFr: 'Ain Kermes', nameAr: 'عين كرمس' },
    { id: 453, wilayaId: 14, nameFr: 'Djebilet Rosfa', nameAr: 'جبيلات الرصفاء' },
    { id: 460, wilayaId: 14, nameFr: 'Madna', nameAr: 'مادنة' },
    { id: 463, wilayaId: 14, nameFr: 'Medrissa', nameAr: 'مدريسة' },
    { id: 476, wilayaId: 14, nameFr: 'Sidi Abderrahmane', nameAr: 'سيدي عبد الرحمن' },
    { id: 459, wilayaId: 14, nameFr: 'Ksar Chellala', nameAr: 'قصر الشلالة' },
    { id: 457, wilayaId: 14, nameFr: 'Guertoufa', nameAr: 'قرطوفة' },
    { id: 474, wilayaId: 14, nameFr: 'Serghine', nameAr: 'سرغين' },
    { id: 486, wilayaId: 14, nameFr: 'Zmalet El Emir Abdelkade', nameAr: 'زمالة الأمير عبد القادر' },
    { id: 469, wilayaId: 14, nameFr: 'Oued Lilli', nameAr: 'وادي ليلي' },
    { id: 477, wilayaId: 14, nameFr: 'Sidi Ali Mellal', nameAr: 'سيدي علي ملال' },
    { id: 454, wilayaId: 14, nameFr: 'Djillali Ben Amar', nameAr: 'جيلالي بن عمار' },
    { id: 462, wilayaId: 14, nameFr: 'Mechraa Safa', nameAr: 'مشرع الصفا' },
    { id: 481, wilayaId: 14, nameFr: 'Tagdempt', nameAr: 'تاقدمت' },
    { id: 450, wilayaId: 14, nameFr: 'Bougara', nameAr: 'بوقرة' },
    { id: 458, wilayaId: 14, nameFr: 'Hamadia', nameAr: 'حمادية' },
    { id: 471, wilayaId: 14, nameFr: 'Rechaiga', nameAr: 'الرشايقة' },
    { id: 484, wilayaId: 14, nameFr: 'Tidda', nameAr: 'تيدة' },
    { id: 467, wilayaId: 14, nameFr: 'Nadorah', nameAr: 'الناظورة' },
    { id: 483, wilayaId: 14, nameFr: 'Tiaret', nameAr: 'تيارت' },
    { id: 464, wilayaId: 14, nameFr: 'Medroussa', nameAr: 'مدروسة' },
    { id: 466, wilayaId: 14, nameFr: 'Mellakou', nameAr: 'ملاكو' },
    { id: 478, wilayaId: 14, nameFr: 'Sidi Bakhti', nameAr: 'سيدي بختي' },
    { id: 446, wilayaId: 14, nameFr: 'Ain Deheb', nameAr: 'عين الذهب' },
    { id: 451, wilayaId: 14, nameFr: 'Chehaima', nameAr: 'شحيمة' },
    { id: 468, wilayaId: 14, nameFr: 'Naima', nameAr: 'النعيمة' },
    { id: 445, wilayaId: 14, nameFr: 'Ain Bouchekif', nameAr: 'عين بوشقيف' },
    { id: 452, wilayaId: 14, nameFr: 'Dahmouni', nameAr: 'دحموني' },
    { id: 470, wilayaId: 14, nameFr: 'Rahouia', nameAr: 'الرحوية' },
    { id: 535, wilayaId: 15, nameFr: 'Mizrana', nameAr: 'ميزرانـــة' },
    { id: 522, wilayaId: 15, nameFr: 'Idjeur', nameAr: 'إيجــار' },
    { id: 510, wilayaId: 15, nameFr: 'Beni-Douala', nameAr: 'بني دوالة' },
    { id: 512, wilayaId: 15, nameFr: 'Beni-Zikki', nameAr: 'بني زيكــي' },
    { id: 527, wilayaId: 15, nameFr: 'Illoula Oumalou', nameAr: 'إيلولة أومـــالو' },
    { id: 489, wilayaId: 15, nameFr: 'Agouni-Gueghrane', nameAr: 'أقني قغران' },
    { id: 493, wilayaId: 15, nameFr: 'Ait Bouaddou', nameAr: 'أيت بــوادو' },
    { id: 538, wilayaId: 15, nameFr: 'Ouadhias', nameAr: 'واضية' },
    { id: 547, wilayaId: 15, nameFr: 'Tizi Ntleta', nameAr: 'تيزي نثلاثة' },
    { id: 488, wilayaId: 15, nameFr: 'Aghribs', nameAr: 'أغريب' },
    { id: 498, wilayaId: 15, nameFr: 'Ait-Chafaa', nameAr: 'أيت شافع' },
    { id: 504, wilayaId: 15, nameFr: 'Akerrou', nameAr: 'أقرو' },
    { id: 507, wilayaId: 15, nameFr: 'Azeffoun', nameAr: 'أزفون' },
    { id: 525, wilayaId: 15, nameFr: 'Iflissen', nameAr: 'إفليـــسن' },
    { id: 544, wilayaId: 15, nameFr: 'Tigzirt', nameAr: 'تيقـزيرت' },
    { id: 505, wilayaId: 15, nameFr: 'Assi-Youcef', nameAr: 'أسي يوسف' },
    { id: 513, wilayaId: 15, nameFr: 'Boghni', nameAr: 'بوغني' },
    { id: 515, wilayaId: 15, nameFr: 'Bounouh', nameAr: 'بونوح' },
    { id: 533, wilayaId: 15, nameFr: 'Mechtras', nameAr: 'مشطراس' },
    { id: 517, wilayaId: 15, nameFr: 'Draa-Ben-Khedda', nameAr: 'ذراع بن خدة' },
    { id: 540, wilayaId: 15, nameFr: 'Sidi Namane', nameAr: 'سيدي نعمان' },
    { id: 548, wilayaId: 16, nameFr: 'Alger', nameAr: 'الجزائر' },
    { id: 549, wilayaId: 17, nameFr: 'Djelfa', nameAr: 'الجلفة' },
    { id: 550, wilayaId: 18, nameFr: 'Jijel', nameAr: 'جيجل' },
    { id: 551, wilayaId: 19, nameFr: 'Sétif', nameAr: 'سطيف' },
    { id: 552, wilayaId: 20, nameFr: 'Saïda', nameAr: 'سعيدة' },
    { id: 553, wilayaId: 21, nameFr: 'Skikda', nameAr: 'سكيكدة' },
    { id: 554, wilayaId: 22, nameFr: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس' },
    { id: 555, wilayaId: 23, nameFr: 'Annaba', nameAr: 'عنابة' },
    { id: 556, wilayaId: 24, nameFr: 'Guelma', nameAr: 'قالمة' },
    { id: 557, wilayaId: 25, nameFr: 'Constantine', nameAr: 'قسنطينة' },
    { id: 558, wilayaId: 26, nameFr: 'Médéa', nameAr: 'المدية' },
    { id: 559, wilayaId: 27, nameFr: 'Mostaganem', nameAr: 'مستغانم' },
    { id: 560, wilayaId: 28, nameFr: 'M\'Sila', nameAr: 'المسيلة' },
    { id: 561, wilayaId: 29, nameFr: 'Mascara', nameAr: 'معسكر' },
    { id: 562, wilayaId: 30, nameFr: 'Ouargla', nameAr: 'ورقلة' },
    { id: 563, wilayaId: 31, nameFr: 'Oran', nameAr: 'وهران' },
    { id: 564, wilayaId: 32, nameFr: 'El Bayadh', nameAr: 'البيض' },
    { id: 565, wilayaId: 33, nameFr: 'Illizi', nameAr: 'إليزي' },
    { id: 566, wilayaId: 34, nameFr: 'Bordj Bou Arréridj', nameAr: 'برج بوعريريج' },
    { id: 567, wilayaId: 35, nameFr: 'Boumerdès', nameAr: 'بومرداس' },
    { id: 568, wilayaId: 36, nameFr: 'El Tarf', nameAr: 'الطارف' },
    { id: 569, wilayaId: 37, nameFr: 'Tindouf', nameAr: 'تندوف' },
    { id: 570, wilayaId: 38, nameFr: 'Tissemsilt', nameAr: 'تيسمسيلت' },
    { id: 571, wilayaId: 39, nameFr: 'El Oued', nameAr: 'الوادي' },
    { id: 572, wilayaId: 40, nameFr: 'Khenchela', nameAr: 'خنشلة' },
    { id: 573, wilayaId: 41, nameFr: 'Souk Ahras', nameAr: 'سوق أهراس' },
    { id: 574, wilayaId: 42, nameFr: 'Tipaza', nameAr: 'تيبازة' },
    { id: 575, wilayaId: 43, nameFr: 'Mila', nameAr: 'ميلة' },
    { id: 576, wilayaId: 44, nameFr: 'Aïn Defla', nameAr: 'عين الدفلى' },
    { id: 577, wilayaId: 45, nameFr: 'Naâma', nameAr: 'النعامة' },
    { id: 578, wilayaId: 46, nameFr: 'Aïn Témouchent', nameAr: 'عين تموشنت' },
    { id: 579, wilayaId: 47, nameFr: 'Ghardaïa', nameAr: 'غرداية' },
    { id: 580, wilayaId: 48, nameFr: 'Relizane', nameAr: 'غليزان' },
    { id: 581, wilayaId: 49, nameFr: 'Timimoun', nameAr: 'تيميمون' },
    { id: 582, wilayaId: 50, nameFr: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار' },
    { id: 583, wilayaId: 51, nameFr: 'Ouled Djellal', nameAr: 'أولاد جلال' },
    { id: 584, wilayaId: 52, nameFr: 'Béni Abbès', nameAr: 'بني عباس' },
    { id: 585, wilayaId: 53, nameFr: 'In Salah', nameAr: 'عين صالح' },
    { id: 586, wilayaId: 54, nameFr: 'In Guezzam', nameAr: 'عين قزام' },
    { id: 587, wilayaId: 55, nameFr: 'Touggourt', nameAr: 'تقرت' },
    { id: 588, wilayaId: 56, nameFr: 'Djanet', nameAr: 'جانت' },
    { id: 589, wilayaId: 57, nameFr: 'El M\'Ghair', nameAr: 'المغير' },
    { id: 590, wilayaId: 58, nameFr: 'El Meniaa', nameAr: 'المنيعة' }
  ];

  const deliveryCompanies = [
    { name: 'Yalidine', logoUrl: null, apiSupported: true },
    { name: 'ZR Express', logoUrl: null, apiSupported: false },
    { name: 'Maystro', logoUrl: null, apiSupported: false },
    { name: 'NOEST', logoUrl: null, apiSupported: false },
    { name: 'Own delivery', logoUrl: null, apiSupported: false }
  ];

  const plans = [
    {
      id: 'starter',
      name: 'Starter',
      priceMonthly: 1500,
      maxOrdersPerMonth: 500,
      maxUsers: 3,
      features: { orderManagement: true, customerManagement: true }
    },
    {
      id: 'growth',
      name: 'Growth',
      priceMonthly: 3500,
      maxOrdersPerMonth: 2000,
      maxUsers: 10,
      features: { orderManagement: true, customerManagement: true, stats: true }
    }
  ];

  await prisma.wilaya.createMany({ data: wilayas, skipDuplicates: true });
  await prisma.commune.createMany({ data: communes, skipDuplicates: true });
  await prisma.deliveryCompany.createMany({ data: deliveryCompanies, skipDuplicates: true });
  await prisma.plan.createMany({ data: plans, skipDuplicates: true });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
